### ISSUE TITLE
Home Depot: Draft stopper product not recognized

### ISSUE THREAD

**Issue by sharonbautista** [mozilla/price-wise#132]
v.0.1.2

This page on Home Depot is not being recognized by the extension as a product page: https://www.homedepot.com/p/Frost-King-E-O-3-3-4-in-x-36-in-Brown-Double-Draft-Stop-for-Doors-or-Windows-DDS1/202022328

<img width="1409" alt="screen shot 2018-09-24 at 1 52 36 pm" src="https://user-images.githubusercontent.com/17853015/45972434-4af6f900-c001-11e8-88a8-d2f346af1ae6.png">

**Comment by Osmose** [comment]
This appears to have been fixed in https://github.com/mozilla/price-wise/pull/275 and should be fixed in v15.0.0 which has been released.
