### ISSUE TITLE
Non-blocking: consider nuanced background price polling when PBM tabs exist

### ISSUE THREAD

**Issue by groovecoder** [mozilla/price-wise#177]
## This does not need to block release

https://github.com/mozilla/webext-commerce/pull/168 went a long way to addressing https://github.com/mozilla/webext-commerce/issues/72.

As [discussed in the PR](https://github.com/mozilla/webext-commerce/pull/168#discussion_r226336955), there may be some additional (non-blocking) enhancements to make for PBM ...

> we could disable background updates while a PBM tab is the active tab.

> maybe disable background updates if there are only PBM windows/tabs open. (I.e., for users who select "Always use Private Browsing" or manually close all regular browsing windows)

**Comment by chuckharmston** [comment]
@muccimoz how disruptive would it be to bring this in to the post-launch milestone?

**Comment by muccimoz** [comment]
> @muccimoz how disruptive would it be to bring this in to the post-launch milestone?

Hi Chuck.  We can review this issue during triage at the team meeting today.

**Comment by muccimoz** [comment]
> @muccimoz how disruptive would it be to bring this in to the post-launch milestone?

Hi Chuck.  This has been added to the milestone.
