### ISSUE TITLE
The "Add This Product" button is wrongly actionable on Walmart shopping cart page when the cart has saved items

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/price-wise#181]
**[Affected versions]:**
- Firefox 62.0.3 and above

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox shopping" add-on (3.0.0) downloaded from https://testpilot.firefox.com/files/shopping-testpilot@mozilla.org/latest.
- Have https://www.walmart.com/ website opened in the browser.
- Have one or more items added in your shopping cart.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Open the shopping cart with the items from prerequisites.
3. Click the "Tracked Products" toolbar button.
4. Click "Add This Product" button and observe the behavior.

**[Expected result]:**
- The "Add This Product" button is not actionable.

**[Actual result]:**
- The "Add This Product" button is actionable.

**[Notes]:**
- If the button is clicked the item is added to the "Tracked Products" list and it has a wrong price displayed.
- This issue is not reproducible on  Amazon, Best Buy, eBay and Home Depot.
- Attached is a screen recording of the issue: 
![cart](https://user-images.githubusercontent.com/40061643/47224864-4980dc80-d3c5-11e8-8318-fd4bafcfb00c.gif)

**Comment by Osmose** [comment]
@erikrose is rewriting our ruleset so that the scores we return are between 0 and 1; that work is a blocker to our current fix for this, which adds a new rule that drops the score for items whose ancestor nodes have `cart` in their classname.

I'll reassign this to myself once his work lands.

**Comment by erikrose** [comment]
In the meantime, somebody could be collecting cart-page samples, which we'll need to pick a confidence threshold.

**Comment by erikrose** [comment]
I revised the ruleset to get each rule between 0..1 and made some other things I guessed were improvements as well. Trained it and got it to 100% on everything: price, title, and image. But then I ran it on the testing corpus and found I had actually made things universally worse. So, I will induct the test set into the training one and go back to the old drawing board!

In the meantime, I'll try to find a way to share my work with you.

**Comment by biancadanforth** [comment]
In talking with Erik, we agreed that it'd be great to include a suitable number of sample pages in our test set to ensure Fathom does **not** find a product on non-product pages for supported sites.

Below is a stub where I was able to reproduce the related, corresponding issue on a particular page. In some cases, the content for the initially reported page has changed, so I included pages displaying a similar symptom and froze them via FathomFox (see below).

Actionable issues where we are finding a "product" when there should be none:
- #245: Should **not** find a product on product subcategory pages for supported sites.
  - [245-home-depot-sub-categories.html](https://www.homedepot.com/b/Tools-Power-Tools-Drills/Cordless/N-5yc1vZc27fZ1z140i3)
- #238 Should **not** find a product on ‘Out of stock’ or ‘product no longer available’ product pages
  - I couldn’t reproduce it with the reported page(s)
  - [238-walmart-out-of-stock.html](https://www.walmart.com/ip/Ninja-Express-Chopper-Red-NJ100/16913480)
- #236: Should **not** find a product on search results pages for supported sites.
  - I couldn’t reproduce it with the reported page(s)
  - [236-ebay-search-results.html](https://www.ebay.com/sch/i.html?_from=R40&_trksid=p2334524.m570.l1313.TR12.TRC2.A0.H0.Xblanket.TRS0&_nkw=blanket&_sacat=0&LH_TitleDesc=0&_osacat=0&_odkw=hammers)
  - [236-best-buy-search-results.html](https://www.bestbuy.com/site/searchpage.jsp?st=cds&_dyncharset=UTF-8&id=pcat17071&type=page&sc=Global&cp=1&nrp=&sp=&qp=&list=n&af=true&iht=y&usc=All+Categories&ks=960&keys=keys)
- #181: Should **not** find a product on a shopping cart page with any number of items.
  - 181-walmart-shopping-cart.html
    - Link is user and session-specific and therefore not shareable

You can find the frozen pages on the Commerce team drive: Commerce > Engineering > extraction_bugs.zip. The naming convention for each frozen page is: `<issue number>-<site>-<page-type>.html`.

@erikrose Would your SoftVision resource be able to help you generate some more example pages for these kinds of symptoms for training? I realize we likely need many more pages to be confident about adressing these issues.

For fun, here is a screenshot of me tracking some "products" extracted by many of these bugs:

![screen shot 2018-11-13 at 2 08 59 pm](https://user-images.githubusercontent.com/17437436/48447961-5ee1f000-e752-11e8-9494-9d12c4fddea7.png)

**Comment by erikrose** [comment]
Sure he could. Do you have a sense what users' current biggest problem is? Is it failed extraction from product pages or these false positives from non-product pages? It seems to me the latter is more of an annoyance than an impediment to use.

**Comment by erikrose** [comment]
Could we put some kind of plug in place so the bad data doesn't get in? (Are we just calling `<` on non-numbers, and that's exploding?)

**Comment by Osmose** [comment]
> Could we put some kind of plug in place so the bad data doesn't get in? (Are we just calling `<` on non-numbers, and that's exploding?) I doubt we'll ever tamp that down to 0%.

We should do both, we just haven't gotten around to it.

**Comment by Osmose** [comment]
This appears to have been fixed in https://github.com/mozilla/price-wise/pull/275 and should be fixed in v15.0.0 which has been released.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue using the latest Price Wise TP (15.0.0) version and the issue is no longer reproducible. Tested on Windows 10x64, Mac 10.13 and Arch Linux 4.16.6 x64.
