### ISSUE TITLE
Collect additional user consent in privacy-sensitive contexts

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/price-wise#184]
In cases where users have `privacy.trackingprotection.enabled` or `privacy.donottrackheader.enabled` set to `true`, or have `network.cookie.cookieBehavior` set to `4`, the  ["no products" screen](https://user-images.githubusercontent.com/23885/47043879-64004f00-d154-11e8-8fb8-347c671f5948.png) should have some additional messaging clarifying that tracking a product will result in the extension making regular requests to the product page on the user's behalf.

@bryanbell would you mind helping us out with that UI here?

This will block launch per @groovecoder.

**Comment by Osmose** [comment]
I'm gonna give this until Wednesday before we implement the backup plan from my comment above.
