### ISSUE TITLE
Collect category 1-2 data and enable background price updates from consenting users in privacy-sensitive contexts

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/price-wise#186]
Moving out a comment from #72:

---

As @johngruen mentioned in Slack yesterday evening, the traditional Test Pilot practice to not send any usage information for users with DNT or Tracking Protection largely exists because Test Pilot experiments generally use Google Analytics to collect data. Since we're using event telemetry, that gives us a bit of leeway.

That said, we still do have a responsibility to be as lean as possible when collecting personal data of users regardless of their privacy settings. To that end, I chatted with @groovecoder this morning to try to work out the right place where we get the usage information we need to evaluate and iterate upon the experiment while still respecting users' privacy and wishes. Here's where I landed:

I do think we should omit any category 3 data (i.e. the aggregate counts of visits to sites we support) if DNT, Tracking Protection or cookie settings indicate a user's intent not to be tracked. I do think we should still collect basic extension interaction metrics in those cases. This is consistent with Firefox, which still collects cat 1 + 2 telemetry data from those users.

I propose amending the above table thusly:

| Feature             | Private Browsing | Do Not Track | Tracking Protection | Reject cookie |
|---------------------|------------------|--------------|---------------------|---------------|
| Price Polling       | `false`          | `true`*      | `true`*             | `true`*       |
| Content Extraction  | `false`          | `true`      | `true`             | `true`       |
| Extension Telemetry (category 1-2) | `false`          | `true`      | `true`             | `true`       |
| Extension Telemetry (category 3) | `false`          | `false`      | `false`             | `false`       |

\* As additional consent to the polling, we should add information to the ["no products" screen](https://user-images.githubusercontent.com/23885/47043879-64004f00-d154-11e8-8fb8-347c671f5948.png) for these users to make sure that they understand that by adding an item to their list, we'll be checking prices on their behalf. This is tracked in #184.

This all meets @groovecoder's goal of making sure we don't make third-party requests for users with DNT/TP without their consent, and does some great proactive reinforcement of our organizational privacy stance.

---

This is not MVP, but we should endeavor to land this before launching.

**Comment by groovecoder** [comment]
There's a `**` on Content Extraction in the table above ... what's that associated with? The additional consent to polling/extraction?

**Comment by chuckharmston** [comment]
> what's that associated with?

It's associated with my scattered brain. Amended and apologies!

**Comment by biancadanforth** [comment]
We will also need to update the "Opt Out" section of METRICS.md accordingly.

**Comment by chuckharmston** [comment]
We did! Conversation starts here: https://bugzilla.mozilla.org/show_bug.cgi?id=1501420#c7

**Comment by biancadanforth** [comment]
@chuckharmston , Re: Row 1, Column 1 of your table: disabling Price Polling in Private Browsing is a little complicated (our conversation starts [here](https://github.com/mozilla/price-wise/pull/168#discussion_r225766093), and is handled by a separate issue (#177 ).

For that reason, we currently do not disable Price Polling in Private Browsing. Would you accept a patch that addressed everything here except that one case, which would be handled by #177 ?

Please note that #177 is not currently in our list of issues to fix during this [post-launch Milestone](https://github.com/mozilla/price-wise/milestone/2).

**Comment by chuckharmston** [comment]
That's definitely fine, although it'd be great to try to bring #177 into that milestone. I've inquired about that on the bug.
