### ISSUE TITLE
Price on page doesn't match price on watch list

### ISSUE THREAD

**Issue by pdehaan** [mozilla/price-wise#206]
I'm trying to add ["Legend of Zelda 'Expansion Pass Bundle'"](https://www.amazon.com/Legend-Zelda-Breath-Wild-Nintendo-Switch/dp/B078JXVGS7/ref=br_asw_pdt-4?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=&pf_rd_r=3FYZX6VQJ2G8DQRFMJTE&pf_rd_t=36701&pf_rd_p=f8585743-c043-4665-80a7-0cc5fe97d596&pf_rd_i=desktop&th=1) to my watch list, but it's adding at $5,485 instead of the $79.98 list price:

![menubar_and_amazon_com__the_legend_of_zelda__breath_of_the_wild_-_nintendo_switch__nintendo_of_america__video_games_and_browser_console_and_apple_iphone_xr_256gb_yellow_mt0h2ll_a_-_best_buy](https://user-images.githubusercontent.com/557895/47397836-06d14400-d6e6-11e8-8614-ae8a9cd8c274.png)

**Comment by muccimoz** [comment]
When I come to the page the default display for me if the Standard Edition priced at $54.85.  When I add it the price shows up at $5485.  In this scenario, there is no switching editions - just adding the one that defaults too when the page loads.

Second scenario, when the page loads and I switch to a different edition ($79.98) the price still shows up as $5485.
