### ISSUE TITLE
The "Add This Product" button is wrongly actionable on the supported websites home page's

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/price-wise#225]
**[Affected versions]:**
- Firefox 63.0 and above

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox shopping" add-on (8.0.0) downloaded from ([download link](https://testpilot.firefox.com/files/shopping-testpilot@mozilla.org/latest)).

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://www.amazon.com/".
2. Click the "Tracked Products" toolbar button.
3. Click "Add This Product" button and observe the behavior.

**[Expected result]:**
- The "Add This Product" button is not actionable.

**[Actual result]:**
- The "Add This Product" button is actionable.

**[Notes]:**
- After "Add This Product" button is clicked, the "Tracked Products" list is minimized, and the addon features are no longer available.
- This issue is reproducible on all shopping websites supported by the experiment.
- This issue is also reproducible if you have products in the "Tracked Products" list.
- Attached is a screen recording of the issue: 
![homepage](https://user-images.githubusercontent.com/40061643/47718193-700a0780-dc50-11e8-9735-8e6d79fdade7.gif)

**Comment by biancadanforth** [comment]
@Softvision-RemusDranca , I believe this issue was resolved when Issue #71 was closed, which landed after v8.0.0 was published. I have published a new version based off `master`, v9.0.0 at the [Test Pilot link](https://testpilot.firefox.com/files/shopping-testpilot@mozilla.org/latest).

Can you please try it and verify if the problem is fixed or not?

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue using  the latest version of the ["Price Wise" add-on (9.0.0)](https://testpilot.firefox.com/files/shopping-testpilot@mozilla.org/latest)  and the issue is no longer reproducible. Tested on Windows 10 x64, Mac 10.13 and Arch Linux.
