### ISSUE TITLE
The trash button, price drop blue icon and the product's name are not vertically aligned

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/price-wise#233]
[Affected versions]:
- Firefox Release v63.0 and up

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest version of the "Price Wise" add-on (8.0.0) downloaded from ([download link](https://testpilot.firefox.com/files/shopping-testpilot@mozilla.org/latest)). 
- A product was already added to the list.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click the "Price Wise" toolbar button and hover the product's section.
3. Observe the vertical alignment of the product's name and the Trash button. 

[Expected result]:
- The product's name is vertically aligned with the Trash button.

[Actual result]:
- The Trash button is positioned higher than the product's name.

[Notes]:
- This is also reproducible with the blue arrow icon which appears when the price drops.
- Here is a screenshot of the issue:
![align](https://user-images.githubusercontent.com/26000308/47789464-423ec480-dd1d-11e8-8048-cae779f097fd.png)
![align2](https://user-images.githubusercontent.com/26000308/47789466-44088800-dd1d-11e8-8221-5e4e929eab4a.png)

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue using the latest Price Wise version (20.0.0) custom build on 01/17/2018, and the issue is no longer reproducible. Tested on Windows 10 x64, Mac 10.13 and Arch Linux 4.16.6 x64.

**Comment by chuckharmston** [comment]
Thank you for the contribution, @sakshi97!
