### ISSUE TITLE
Wrong item description is displayed when adding an alert

### ISSUE THREAD

**Issue by poubina** [mozilla/price-wise#236]
**[Affected versions]:**
- Firefox 63.0

**[Affected Platforms]:**
- Windows 10 (due to hardware/software restrictions bug will verified on remaining OSes on following days).

**[Prerequisites]:**
- Price Wise installed from https://testpilot.firefox.com/files/shopping-testpilot@mozilla.org/latest

**[Steps to reproduce]:**
1. Open the browser and navigate to "http://www.ebay.com/"
2. Fill in site's search bar with value "Motorola" and search (a list of Motorola products will be displayed).
3. Click on Price Wise.
4. Click "Add This Product" button and observe the behavior.

**[Expected result]:**
- The "Add This Product" button is not actionable (we have a list of products after searching).

**[Actual result]:**
- The "Add This Product" button is actionable and the first item of the list is added with the wrong description.

**[Notes]:**
- See screenshots attached.
![motorola ebay](https://user-images.githubusercontent.com/44272078/47807640-5f729380-dd1b-11e8-814e-78259691bd7c.png)

**Comment by Osmose** [comment]
This appears to have been fixed in https://github.com/mozilla/price-wise/pull/275 and should be fixed in v15.0.0 which has been released.

**Comment by Osmose** [comment]
This appears to have been fixed in https://github.com/mozilla/price-wise/pull/275 and should be fixed in v15.0.0 which has been released.

**Comment by poubina** [comment]
I have verified this issue using the latest version of the "Price Wise" add-on (15.0.0) and the issue is no longer reproducible.
