### ISSUE TITLE
The green badge is not displayed if opening a product's link in a new tab

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/price-wise#237]
[Affected versions]:
- Firefox Release v63.0 

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a Firefox profile with the latest version of the "Price Wise" add-on (8.0.0) downloaded from ([download link](https://testpilot.firefox.com/files/shopping-testpilot@mozilla.org/latest)). 

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to Walmart website.
3. Middle click on a product.
4. Wait for the products's page to load and click on the newly opened tab.
5. Observe the Price Wise badge.

[Expected result]:
- The green badge is displayed.

[Actual result]:
- The initial state badge is displayed.

[Notes]:
- This issue is reproducible only with the Walmart website.
- This is also reproducible when opening the link from the context menu.
- Here is a screen recording of the issue:

![badge disappear](https://user-images.githubusercontent.com/26000308/47855547-91ecc100-dded-11e8-8d24-a83404af3776.gif)

**Comment by chuckharmston** [comment]
@Osmose Not sure if the add-on is structured in a way that you can do this, but I've worked around similar issues by ensuring that the browserAction's state is only changed as the result of requests where `details.frameId === 0`.

**Comment by Osmose** [comment]
> @Osmose Not sure if the add-on is structured in a way that you can do this, but I've worked around similar issues by ensuring that the browserAction's state is only changed as the result of requests where `details.frameId === 0`.

The annoying thing about this bug is that it isn't our code that's resetting the browser action. It's the in-product extension code mistakenly identifying an iframe load as a top level page load and resetting it. The relevant bug is [bug 1493470](https://bugzilla.mozilla.org/show_bug.cgi?id=1493470), but it landed in 64, so we have a single release cycle of dealing with this before it stops being a problem.

**Comment by Osmose** [comment]
@SoftVision-CarmenFat Can you confirm whether you see the issue with this build of the add-on? https://usercontent.irccloud-cdn.com/file/LCrGGoJF/price_wise-8.0.1-signed.xpi

**Comment by Osmose** [comment]
The fix in question has not been released, 8.0.1 is just a test build I made. We still need to fix this.

**Comment by SoftVision-CarmenFat** [comment]
I have verified this issue using the latest Price Wise version (15.0.0) from Test Pilot platform and the issue is no longer reproducible. Tested on Windows 10, Mac 10.13 and Arch Linux 4.16.6 x64.
