### ISSUE TITLE
Allow data: URIs for product images

### ISSUE THREAD

**Issue by Osmose** [mozilla/price-wise#248]
Amazon uses `data:` URIs for product images in their initial page payload. After the page is focused, they change the image URLs to `https` images, presumably for initial page load performance reasons.

If you open an Amazon product page in a new tab ([example](https://www.amazon.com/Aduro-Solid-Grip-Phone-Holder-Desk/dp/B01HDZJ1ZE/ref=br_msw_pdt-4/146-6250364-5227811?_encoding=UTF8&smid=AY3SA6XQV4F15&pf_rd_m=ATVPDKIKX0DER&pf_rd_s=&pf_rd_r=5E9J6NK3RTSTZVZ1XCHX&pf_rd_t=36701&pf_rd_p=e45ffc42-9164-4bf4-a2b6-9dd0d40c06f6&pf_rd_i=desktop)) and wait at least 10 seconds before focusing the new tab, upon viewing the page the toolbar icon will not indicate that a product can be saved until you refresh the tab. This is due to our extraction methods rejecting the `data:` URI for the product image while the tab is unfocused.

I checked with @pauljt and he agreed that allowing `data:` URIs (and checking that the mimetype matches an allowed image mimetype) is acceptable, so we should update our product validation to accept `data:` URIs whose path starts with one of:

- `image/gif;`
- `image/png;`
- `image/jpeg;`
- `image/svg+xml;`
- `image/webp;`

**Comment by prateek76** [comment]
@Osmose I want to work on this
