### ISSUE TITLE
The Price Wise toolbar button has a different color than the other buttons while using all the Firefox themes

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/price-wise#252]
[Affected versions]:
- Firefox Release v63.0.1 and up

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a Firefox profile with the latest version of the "Price Wise" add-on (9.0.0) downloaded from ([download link](https://testpilot.firefox.com/files/shopping-testpilot@mozilla.org/latest)). 

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Observe the "Price Wise" toolbar button.

[Expected result]:
- The button has the same grey color as the other buttons.

[Actual result]:
- The button is almost black.

[Notes]:
- The "Price Wise" toolbar button has different colors than the other buttons on all themes: Default, Dark and Light ones.
- Please see the following page related to Photon iconography: https://design.firefox.com/photon/visuals/iconography.html
- Here is a screenshot of the issue compared to the Test Pilot toolbar button:

![icons](https://user-images.githubusercontent.com/26000308/48139826-1c329a80-e2b0-11e8-9627-639d66edab35.png)

**Comment by Osmose** [comment]
I suspect this is because our SVGs have `fill="context-fill"` so that they can be assigned a context-specific fill color, but are missing `fill-opacity="context-fill-opacity"` to do the same for their opacity.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue using the latest Price Wise version (16.0.0) custom build on 11/29/2018, and the issue is no longer reproducible. Tested on Windows 10 x64, Mac 10.13 and Ubuntu 18.04 x64.
