### ISSUE TITLE
Wrong survey screen with empty options - v. 10.0.0 

### ISSUE THREAD

**Issue by poubina** [mozilla/price-wise#254]
[Affected versions]:
    Firefox Release v63.0.1 and up

[Affected Platforms]:
    Windows 10
    Ubuntu
    Mac

[Prerequisites]:
    Have a Firefox profile with the latest version of the "Price Wise" add-on (10.0.0) downloaded from [download link](https://testpilot.firefox.com/files/shopping-testpilot@mozilla.org/latest)

[Steps to reproduce]:
    1) Open the browser with the profile from prerequisites.
    2) Click on "Price Wise" (door hanger) -> "Send Feedback" option and observe the screen that will open.

[Expected result]:
    A new tab is open with the correct survey

[Actual result]:
    A new tab is open with questions that are missing.

[Notes]:
    Here is a screen shot of the issue

![wrong survey](https://user-images.githubusercontent.com/44272078/48200893-4a12f000-e33f-11e8-97be-86d60ff849ec.png)

**Comment by Osmose** [comment]
I can confirm that the survey at https://www.surveygizmo.com/s3/4649085/Price-Wise-Feedback is no longer blank. Thanks Teon!

**Comment by poubina** [comment]
I have verified this issue using the latest version of the "Price Wise" add-on (15.0.0) and the issue is no longer reproducible.
