### ISSUE TITLE
Event telemetry is not recorded on Release

### ISSUE THREAD

**Issue by biancadanforth** [mozilla/price-wise#258]
When Issues #156 , #157 and #158 were closed, none of the registered telemetry events were given the requisite [`record_on_release` key](https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/telemetry/collection/events.html#registerevents) to ensure they were recorded in the Release channel. When this key is omitted, the associated events are not recorded by default.

As a result, extension event telemetry is not currently being recorded in Release. We should fix that!

**Comment by chuckharmston** [comment]
@SoftVision-CarmenFat @Softvision-RemusDranca @poubina Want to call your attention to this; assuming a patch for this lands on 8 Nov, would you mind making sure this gets tested on 9 Nov? Bianca will leave some testing instructions here.

Thank you!
