### ISSUE TITLE
Not able to add product to price wise, add button is grey

### ISSUE THREAD

**Issue by pdehaan** [mozilla/price-wise#265]
via https://github.com/mozilla/testpilot/issues/3983 /cc @BruceAWilliams

**Comment by pdehaan** [comment]
@BruceAWilliams: Which site were you trying to add a product from? (amazon.com? homedepot.com?, other?)

**Comment by Osmose** [comment]
@BruceAWilliams As @pdehaan said, the full URL of the product you're trying to add is needed for us to debug the issue. Thank you!

@koevskinikola Only the US Amazon store is currently supported, so not being able to add products on those domains is expected.

**Comment by pdehaan** [comment]
@koevskinikola The full list of supported domains can be found at https://github.com/mozilla/price-wise/blob/00eaff21bad7d4875c195a53d4d798c5e8b185a3/src/state/vendors.js#L22-L53

**Comment by sigil88** [comment]
> 
> 
> @BruceAWilliams As @pdehaan said, the full URL of the product you're trying to add is needed for us to debug the issue. Thank you!
> 
> @koevskinikola Only the US Amazon store is currently supported, so not being able to add products on those domains is expected.

I really think "US only" needs to be mentioned on the test pilot page - I just installed it assuming it would work with the UK site as it doesn't mention "US only" anywhere.

**Comment by saiyerniakhil** [comment]
Waiting for it to arrive in Other countries too

**Comment by jennajon** [comment]
Ditto on bug report of not being able to add items from Amazon USA.
Uninstalled, reinstalled and restarted FF-does not work
URL of item from Amazon USA: https://www.amazon.com/dp/B01EXQ0ZV0/?coliid=I3EGJ8X93UM2U9&colid=2ICW3SMNVOTL5&psc=0&ref_=lv_ov_lig_dp_it

**Comment by Osmose** [comment]
> I really think "US only" needs to be mentioned on the test pilot page - I just installed it assuming it would work with the UK site as it doesn't mention "US only" anywhere.

Excellent point, this is now being worked on in https://github.com/mozilla/price-wise/issues/266.

**Comment by larrygiddens** [comment]
Likewise, I have a gray "add this product bar" on Walmart and Amazon, in normal and incognito mode.  Here's the URL:  https://www.amazon.com/PLAYMOBIL%C2%AE-5684-PLAYMOBIL-Pony-Farm/dp/B01B133YPC

**Comment by Osmose** [comment]
This appears to have been fixed in https://github.com/mozilla/price-wise/pull/275 and should be fixed in v15.0.0 which has been released.

Thanks for the issue!
