### ISSUE TITLE
Add more documentation (here and possibly on Test Pilot site) around supported domains

### ISSUE THREAD

**Issue by pdehaan** [mozilla/price-wise#266]
"Amazon" is perhaps too vague, and we should clarify that it is only currently supported on `/^(www\.|smile\.)?amazon.com$/`

**Comment by biancadanforth** [comment]
@cherrypark, @javaun, @chuckharmston ,

- [ ] Should we do anything specific on the Test Pilot pages, and/or other official Mozilla communications pages about better communicating this?
- [ ] Should we do anything specific in the extension itself to better communicate this? Currently, we communicate this to users on the Onboarding popup for the extension only (below).

![screen shot 2018-11-13 at 11 50 34 am](https://user-images.githubusercontent.com/17437436/48439109-609fb980-e73a-11e8-9dba-a25cb5b8f703.png)

**Comment by biancadanforth** [comment]
For in-product, we could change the first sentence to something like this:

BEFORE:
> Add products you want to buy from Amazon, Best Buy, eBay, Home Depot, and Walmart to your Price Watcher list, and Firefox will notify you if the price drops.

AFTER:
> Add products you want to buy from Amazon, Best Buy, eBay, Home Depot, and Walmart to your Price Watcher list (US domains only for now), and Firefox will notify you if the price drops.

What do you all think?

**Comment by BrianNJones** [comment]
@biancadanforth copy deck updated. Thanks for the catch!

**Comment by biancadanforth** [comment]
@BrianNJones , Great thank you! Let me know if you would like any copy to change in the extension UI itself (I make a proposal in [this comment](https://github.com/mozilla/price-wise/issues/266#issuecomment-439456179) for the Onboarding popup).

I will leave this issue open for a few more days; If I don't hear anything, I will assume that [changes to the Test Pilot pages](https://github.com/mozilla/testpilot/pull/3988) and SUMO (support.mozilla.org) page (handled by @marniepw ) are sufficient.

**Comment by BrianNJones** [comment]
@biancadanforth, small thing, but perhaps we don't want to assume "products you want to buy?" I went with "products you're interested in."

**Comment by biancadanforth** [comment]
@BrianNJones Thank you for your feedback. Just to confirm, are you suggesting we change the Onboarding popup copy to:

> Add products you're interested in from Amazon, Best Buy, eBay, Home Depot, and Walmart to your Price Watcher list (US domains only for now), and Firefox will notify you if the price drops.

I'm also wondering if we should change "Price Watcher" to "Price Wise"... I think that may be a relic from an earlier time before the product's name was finalized. What do you think?

**Comment by biancadanforth** [comment]
@chuckharmston , I don't see the Test Pilot pages ([the home page](https://testpilot.firefox.com/) and [the Price Wise page](https://testpilot.firefox.com/experiments/price-wise)) updated yet despite the issue being merged 18 hours ago. Is that expected?

**Comment by BrianNJones** [comment]
@biancadanforth, thank you for catching my "Price Watcher" typo! Please use: Add products from Amazon and AmazonSmile, Best Buy, eBay, Home Depot and Walmart (U.S. domains only for now). When Price Wise finds a price drop, the add-on gives you a heads-up about the lower price.
