### ISSUE TITLE
Add support for more country-specific Amazon sites

### ISSUE THREAD

**Issue by pdehaan** [mozilla/price-wise#269]
Currently only USA-centric [smile|www].amazon.com is supported, but there have been a few requests for more country-specific Amazon domains added (see #265 and #266).

Not sure if this is a complete Amazon country list, but I noticed it at the bottom of one of the [localized Amazon sites](https://www.amazon.com.au/ref=footer_au) (but oddly not amazon.com):

| COUNTRY | SITE
|:--------|:-----
Brazil | https://www.amazon.com.br
Canada | https://www.amazon.ca
China | https://www.amazon.cn
France | https://www.amazon.fr
Germany | https://www.amazon.de
India | https://www.amazon.in
Italy | https://www.amazon.it
Japan | https://www.amazon.co.jp
Mexico | https://www.amazon.com.mx
Netherlands | https://www.amazon.nl
Spain | https://www.amazon.es
Turkey | https://www.amazon.com.tr
United Kingdom | https://www.amazon.co.uk
United States | https://www.amazon.com

**Comment by mrforsythexeter** [comment]
If this is going to not be completed, please use geo detection to not offer it. This will not help the test.

**Comment by biancadanforth** [comment]
Thank you for the suggestion. We are in the process of adding some clarification about the restrictions via #266 to the Test Pilot pages ([the home page](https://testpilot.firefox.com/) and [the Price Wise page](https://testpilot.firefox.com/experiments/price-wise)) and [support page](https://support.mozilla.org/en-US/kb/new-test-pilot-experiments).

Though it may be a good idea to also display a different page at the point of install (i.e. the Test Pilot pages) for folks trying to install the extension in geos we currently do not support. @chuckharmston , what do you think?

It may also be possible to detect geo in the extension and display a different popup for those users, but we'd need some guidance on what that would look like.

**Comment by chuckharmston** [comment]
This is a much more complicated ask than it appears, as it requires us to be aware of multiple currencies, something we are able to punt by restricting it to US-based sites. One of the reasons this is in Test Pilot is that we want to validate the concept before investing in this sort of intelligence.

We do have more information about this restriction committed to Test Pilot, which will be included with its next deploy. Unfortunately, Test Pilot does not offer the ability to geo-detect, so we are only able to restrict based on the `Accept-Languages` header.
