### ISSUE TITLE
Amazon Entry shows price drop, but Amazon site does not

### ISSUE THREAD

**Issue by kenandersonjr** [mozilla/price-wise#273]
Have a saved entry for an amazon item,  the price-wise drop down shows a price drop, but when I click through the item  to the amazon site, it shows the original price.  
![image](https://user-images.githubusercontent.com/45101199/48632909-1f084c00-e990-11e8-9efd-b422740065be.png)

**Comment by pdehaan** [comment]
I _think_ this is the URL in question: https://www.amazon.com/TCL-55S517-55-Inch-Ultra-Smart/dp/B07987KQBN/ref=sr_1_7_sspa?ie=UTF8&qid=1542389988&sr=8-7-spons&keywords=tcl+55-inch&refinements=p_89%3ATCL&psc=1

The 55" is currently $429.50, but I see the smallest model (the 43") is currently $319.50, which is maybe the price that it's detecting as the new price.

**Comment by Osmose** [comment]
Thanks for the report! I can verify that we're extracting the wrong price here; when I try to add the 55" TV it pulls the price for the 43" TV.

**Comment by Osmose** [comment]
This appears to have been fixed in https://github.com/mozilla/price-wise/pull/275 and should be fixed in v15.0.0 which has been released.

Thanks for the issue!
