### ISSUE TITLE
In-Product Recruiting for Cyber Monday User Research Study

### ISSUE THREAD

**Issue by sharonbautista** [mozilla/price-wise#274]
The Price Wise team would like to recruit participants for a user research study from within the Price Wise UI. The UI should be accessible to people already using the Price Wise experiment, exact location TBD by UX. 

The in-product call-to-action (CTA) should read: 

> Help us improve Price Wise by participating in a research study. Take [this 5-minute survey](https://www.surveygizmo.com/s3/4693160/Price-Wise-Research-Study-Participant-Screener) to learn more about the study and see if you're a fit.

The link within the CTA will take users to a screener survey. The CTA with link should appear in the Price Wise UI as early as Friday, November 16 and appear through Friday, November 23.

**Comment by biancadanforth** [comment]
Once we have a location, we can complete this task.

Do we want this message in both the empty onboarding popup and the standard list view popup? I imagine most users will have added at least one item at this point, so it may be a good idea to put this message in both.

**Comment by sharonbautista** [comment]
Yes, I think the bottom of the Product list for people who have created at least one alert is our best bet. My guess is that the CTA will be less visible in the onboarding popup since there's a decent amount of text there already.

**Comment by bryanbell** [comment]
How's this? 
<img width="1347" alt="image" src="https://user-images.githubusercontent.com/228979/48653924-812b7600-e9bd-11e8-8b98-887c7acc5204.png">

**Comment by biancadanforth** [comment]
@bryanbell Looks good! Thank you. We will implement this Monday. Can you send us the icon asset? I don't see it in the set of icons at design.firefox.com.

**Comment by biancadanforth** [comment]
@sharonbautista , @chuckharmston I noticed the survey URL has a "surveygizmo" domain instead of a Mozilla-branded domain (related: #262 ), are we certain we want to use this one instead of a Mozilla-branded domain URL?

**Comment by bryanbell** [comment]
![image](https://user-images.githubusercontent.com/228979/48738994-7b28d580-ec07-11e8-8f89-7caf25b86b51.png)

**Comment by sharonbautista** [comment]
Updated survey link to with Mozilla URL and Firefox branding: https://qsurvey.mozilla.com/s3/Price-Wise-Research-Study

**Comment by sharonbautista** [comment]
@biancadanforth Yes, we can remove the study recruitment now. Thank you.
