### ISSUE TITLE
Price drops on competitor sites

### ISSUE THREAD

**Issue by yoasif** [mozilla/price-wise#279]
Right now, the price wise extension reloads the page the user submits to track pricing. This is interesting if you expect the price to go down on that page, or if the user has loyalty to a particular retailer. 

I am less loyal to a particular retailer, however, and so I would like to see price wise find lower prices on competitor sites. 

So for example, I could track a TV on best buy, but price wise could alert me of a better price on amazon.

**Comment by biancadanforth** [comment]
Thank you for submitting feedback. Being able to compare prices across retailers would be a great capability. That is currently beyond the scope of our experiment, but certainly that is a consideration should we decide to make this a permanent feature in Firefox.

I can't speak from the product side, but there are some technical challenges there. In particular, we base our price checks off the URL for the page, which we are given by the user when they add a product. We would therefore need to know the URL for the other retailers' products to perform price checks on those sites.

**Comment by chuckharmston** [comment]
Thanks for the feedback, @yoasif!

As @biancadanforth mentioned, this feature is something we’ve discussed, and though it would be excellent in a graduated experiment, it’s not likely to be a part of this limited experiment. Since it’s on our roadmap, I’ll be closing this issue.
