### ISSUE TITLE
There is an inconsistency between the minimum age restriction in the message displayed under the "Next" button and the question asked on the "Research study" page 

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/price-wise#283]
**[Affected versions]:**
- Firefox 63.0.3 and above

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile with with the Price Wise experiment (v.15.0.0) installed from Test Pilot.
- Have a product in the Price Wise "Product list".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Tracked Products" toolbar button. 
3. Click the "Help us improve Price Wise" button and click the "Take a 5 minute survey" button.
4. Click the "Next" button and observe the minimum age restriction displayed on the page.

**[Expected result]:**
- The age displayed in the message is the same as in the survey question.

**[Actual result]:**
- In the survey question the minimum age is 18 and in the message displayed under the "Next" button, the minimum age displayed is 19. 

**[Notes]:**
- Attached is a screen recording of the issue: 
![age](https://user-images.githubusercontent.com/40061643/48855324-8113e780-edbc-11e8-850e-b5a6bbd4c730.gif)

**Comment by biancadanforth** [comment]
Thanks for filing this issue. @sharonbautista, can you take a look? For some reason I can't officially assign this issue to you. Perhaps if you accept my collaborator invite I just sent as well?

**Comment by sharonbautista** [comment]
Thank you. I just double checked with Alicia Gray. The age is now consistent, 19 in the survey question and in the footer.

**Comment by biancadanforth** [comment]
I can confirm this has changed; thanks Sharon!
