### ISSUE TITLE
Walmart: Toilet Paper not listed as product

### ISSUE THREAD

**Issue by javaun** [mozilla/price-wise#81]
Extension v0.1.0

Clicked from Resolve carpet cleaner > Puffs (added) to Toilet paper. Charmin TP also did not register as a product. I did not see an offer to track this in the hanger

https://www.walmart.com/ip/Charmin-Ultra-Strong-Toilet-Paper-12-Mega-Rolls/44886117?athcpid=44886117&athpgid=athenaItemPage&athcgid=null&athznid=collection&athieid=v0&athstid=CS020&athguid=466001f5-d06c18f9-624bc8bc479f04bd&athena=true

![screen shot 2018-08-29 at 10 38 11 pm](https://user-images.githubusercontent.com/126270/44826308-6296b980-abdc-11e8-9802-75c971ecc82c.png)

**Comment by Osmose** [comment]
This appears to have been fixed in https://github.com/mozilla/price-wise/pull/275 and should be fixed in v15.0.0 which has been released.
