### ISSUE TITLE
Best Buy: TV product page not recognized

### ISSUE THREAD

**Issue by javaun** [mozilla/price-wise#82]
Extension v0.1.0

On this TV page: I do not see an offer to "track" in the hanger

https://www.bestbuy.com/site/samsung-65-class-led-q6f-series-2160p-smart-4k-uhd-tv-with-hdr/6202109.p?skuId=6202109

![screen shot 2018-08-29 at 10 42 28 pm](https://user-images.githubusercontent.com/126270/44826452-1730db00-abdd-11e8-92d1-41d68af1035e.png)

**Comment by Osmose** [comment]
This appears to have been fixed in https://github.com/mozilla/price-wise/pull/275 and should be fixed in v15.0.0 which has been released.
